stages:
  - mirror
  - package
  - deploy

include:
  - project: 'devops/containers/kaniko-docker-build'
    ref: v1.0.6
    file: '/.build_with_kaniko.yml'

######################## TEMPLATES ######################
.build-docker-image:
  
  extends: .build_with_kaniko
  except:
    refs:
      - tags
      - master
      - schedules

.push-docker-image:
  extends: .build_with_kaniko
  only:
    refs:
      - tags
      - master
  except:
    refs:
      - schedules

######################## JOBS ########################
#MIRRORING
git-mirror-upstream_master:
  stage: mirror
  only:
    - schedules
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
    UPSTREAM_REPO: "https://github.com/devshawn/kafka-gitops.git"
  script:
    - git remote rm upstream || true
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote remove origin
    - git remote add origin git@sources.devtools.local:${CI_PROJECT_PATH}.git
    - git remote add upstream ${UPSTREAM_REPO}
    - git fetch --all
    - git checkout upstream_master || git checkout -b upstream_master upstream/master
    - git merge upstream/master --ff
    - git push origin HEAD:upstream_master

build-docker:
  stage: package
  extends: .build-docker-image
  variables:
    KANIKO_EXECUTOR_EXTRA_OPTS: "--no-push"
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - .m2/repository
    - target
    policy: pull

push-docker:
  stage: deploy
  extends: .push-docker-image
  variables:
    KANIKO_EXECUTOR_EXTRA_OPTS: ""
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - .m2/repository
    - target
    policy: pull

